name: Liquibase example
on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: benjaminehowe/cockroachdb-single-node
  VERSION: v22.2.7

jobs:
  liquibase-update:
    runs-on: ubuntu-latest
    services:
      crdb:
        image: ghcr.io/benjaminehowe/cockroachdb-single-node:v22.2.7
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - "26257:26257"
          - "8080:8080"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Wait until CockroachDB passes healthcheck
        run: until [ $(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/health?ready=1) == '200' ]; do :; done
      - name: "Liquibase update (service container)"
        uses: liquibase-github-actions/update@v4.19.0
        with:
          changelogFile: "changelog-main.xml"
          url: "jdbc:postgresql://crdb:26257/defaultdb?sslmode=disable"
          username: "root"
      - name: "Liquibase update (dev cluster)"
        uses: liquibase-github-actions/update@v4.19.0
        with:
          changelogFile: "changelog-main.xml"
          url: "jdbc:postgresql://beh-dev-7610.8nj.cockroachlabs.cloud:26257/liquibase?sslmode=verify-full&sslrootcert=/github/workspace/cockroachdb-root.crt"
          username: "liquibase-demo-gha"
          password: ${{ secrets.COCKROACH_DEV_PASSWORD }}
