name: Liquibase example
on: push

jobs:
  liquibase-update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      # Using Docker Compose instead of Service Containers due to https://github.com/orgs/community/discussions/52675
      - name: Run CockroachDB container
        run: docker compose up -d
      - name: Wait until CockroachDB passes healthcheck
        run: until [ $(/usr/bin/docker inspect --format='{{json .State.Health}}' cockroachdb-liquibase-crdb-1 | jq '.Status') == '"healthy"' ]; do :; done
      - run: docker ps -a
      - name: "Liquibase update"
        uses: liquibase-github-actions/update@v4.19.0
        with:
          changelogFile: "changelog-main.xml"
          url: "jdbc:postgresql://cockroachdb-liquibase-crdb-1:26256/defaultdb?sslmode=disable"
          username: "root"
